{% set version = "1.98-1.20" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcurl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RCurl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RCurl/RCurl_{{ version }}.tar.gz
  sha256: 91ec442673597261115354e791f14b59fc8dc339010ae775e03c185970a48c1b
  patches:
    - patches/0001-minimal-ucrt-libs.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bitops                     # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bitops
    - libcurl
    - liblzma-devel
    - libxml2-devel                      # [not win]
    - zlib
  run:
    - r-base
    - r-bitops

test:
  commands:
    - $R -e "library('RCurl')"           # [not win]
    - "\"%R%\" -e \"library('RCurl')\""  # [win]

about:
  home: http://www.omegahat.net/RCurl
  license: BSD-3-Clause
  summary: A wrapper for 'libcurl' Provides functions to allow one to compose general HTTP requests and provides convenient functions to fetch URIs, get & post forms, etc. and process the results returned by the Web server. This provides a great deal of control over the HTTP/FTP/... connection and the form of the 
    request while providing a higher-level interface than is available just using R socket connections.  Additionally, the underlying implementation is robust and extensive, supporting FTP/FTPS/TFTP (uploads and downloads), SSL/HTTPS, telnet, dict, ldap, and also supports cookies, redirects, authentication, etc.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
